using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using HiddenFeaturesExplorer.Models;

namespace HiddenFeaturesExplorer.Services;

public static class FeatureDatabase
{
    public static List<WindowsFeature> GetAllFeatures()
    {
        return new List<WindowsFeature>
        {
            // ========== PRODUCTIVITY ==========
            new WindowsFeature
            {
                Id = "god-mode",
                Name = "God Mode",
                SimpleExplanation = "Put hundreds of Windows settings in one easy-to-browse folder.",
                DetailedExplanation = "God Mode is a special folder that gives you instant access to over 200 Windows control panel settings in a single list view.",
                WhatItDoes = "Creates a special folder with all Windows settings organized in one place.",
                WhyUseful = "Instead of hunting through multiple menus and settings pages, you get everything in a clean, searchable list.",
                HowToAccess = "Create a new folder and rename it to: GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "find hidden settings", "all windows settings", "control panel", "system settings", "access everything" },
                UsefulnessScore = 9.5,
                DiscoveryDifficulty = 7.0,
                CanLaunch = true,
                LaunchCommand = "shell:::{ED7BA470-8E54-465E-825C-99712043E01C}",
                IconGlyph = "\uE7C3",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "virtual-desktops",
                Name = "Virtual Desktops",
                SimpleExplanation = "Create separate desktop workspaces for different tasks.",
                DetailedExplanation = "Virtual Desktops let you create multiple isolated desktop environments. You can have one desktop for work, one for personal use, one for research, etc.",
                WhatItDoes = "Creates multiple virtual workspaces you can switch between.",
                WhyUseful = "Keep your work organized by separating different projects or tasks into their own desktop spaces.",
                HowToAccess = "Press Win + Tab, then click 'New Desktop' at the top.",
                KeyboardShortcut = "Win + Tab",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "multiple desktops", "separate workspaces", "organize windows", "virtual desktop", "clean desktop" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 4.0,
                CanLaunch = true,
                LaunchCommand = "ms-settings:multitasking",
                IconGlyph = "\uE8A0",
                AccentColor = "#6B4FCF"
            },
            new WindowsFeature
            {
                Id = "clipboard-history",
                Name = "Clipboard History",
                SimpleExplanation = "Remember everything you copy, not just the last thing.",
                DetailedExplanation = "Windows can keep a history of everything you copy to the clipboard. You can then paste from this history instead of re-copying.",
                WhatItDoes = "Keeps a running list of items you've copied (text, images, links).",
                WhyUseful = "Never lose something you copied because you copied something else. Access your full clipboard history anytime.",
                HowToAccess = "Press Win + V to view clipboard history. Enable it in Settings > System > Clipboard.",
                KeyboardShortcut = "Win + V",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "copy paste history", "clipboard", "multiple clipboard", "paste older items", "remember copied text" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                SettingsUri = "ms-settings:clipboard",
                IconGlyph = "\uE16D",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "snap-layouts",
                Name = "Snap Layouts & Snap Groups",
                SimpleExplanation = "Arrange windows perfectly with one click.",
                DetailedExplanation = "Snap Layouts let you quickly arrange windows in predefined layouts by hovering over the maximize button. Snap Groups remember your layouts.",
                WhatItDoes = "Provides pre-defined window arrangements for multitasking.",
                WhyUseful = "Quickly organize multiple windows without manually resizing and positioning each one.",
                HowToAccess = "Hover over the maximize button of any window to see layout options, or drag windows to screen edges.",
                KeyboardShortcut = "Win + Arrow Keys",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                MinVersion = WindowsVersionRequirement.Windows11Version21H2,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "arrange windows", "split screen", "multitask", "organize windows", "window layout", "side by side" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 5.0,
                CanLaunch = true,
                LaunchCommand = "ms-settings:multitasking",
                IconGlyph = "\uE8A0",
                AccentColor = "#00B294"
            },
            new WindowsFeature
            {
                Id = "focus-assist",
                Name = "Focus Sessions / Focus Assist",
                SimpleExplanation = "Block distractions and stay focused on your work.",
                DetailedExplanation = "Focus Sessions integrate with the Clock app to help you concentrate. Focus Assist (older name) blocks notifications during focus time.",
                WhatItDoes = "Reduces distractions by managing notifications and providing a timer for focused work.",
                WhyUseful = "Helps you concentrate by silencing non-critical notifications and tracking your work sessions.",
                HowToAccess = "Open the Clock app and go to Focus Sessions, or Settings > System > Focus Assist.",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                SettingsUri = "ms-settings:focus",
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "focus", "concentrate", "block notifications", "do not disturb", "productivity timer", "pomodoro" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE9D9",
                AccentColor = "#FF8C00"
            },
            new WindowsFeature
            {
                Id = "voice-typing",
                Name = "Voice Typing",
                SimpleExplanation = "Dictate text anywhere using your voice.",
                DetailedExplanation = "Windows has a built-in speech-to-text engine that works in any text field. Press Win + H and start talking.",
                WhatItDoes = "Converts your spoken words into text in any text field.",
                WhyUseful = "Type faster, reduce typos, and give your hands a rest. Great for long documents or emails.",
                HowToAccess = "Press Win + H in any text field to start voice typing.",
                KeyboardShortcut = "Win + H",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "dictate", "speech to text", "voice type", "talk to type", "transcribe", "voice input" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE767",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "task-view-timeline",
                Name = "Task View / Timeline",
                SimpleExplanation = "See everything you've been working on, organized by time.",
                DetailedExplanation = "Task View shows all open windows at a glance. Timeline (Windows 10) shows your recent activity history across devices.",
                WhatItDoes = "Shows an overview of all open windows and recent activity.",
                WhyUseful = "Quickly find and switch to any window or resume recent work without searching.",
                HowToAccess = "Press Win + Tab to open Task View.",
                KeyboardShortcut = "Win + Tab",
                Category = FeatureCategory.Productivity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "see all windows", "switch windows", "recent work", "task view", "activity history" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE77C",
                AccentColor = "#6B4FCF"
            },

            // ========== FILE MANAGEMENT ==========
            new WindowsFeature
            {
                Id = "quick-access",
                Name = "Quick Access & Pinning",
                SimpleExplanation = "Pin your most-used folders to File Explorer for instant access.",
                DetailedExplanation = "Quick Access lets you pin folders and recent files to the top of File Explorer so you never have to navigate deep folder structures again.",
                WhatItDoes = "Pins frequently used folders and files to the top of File Explorer.",
                WhyUseful = "Saves time by giving you one-click access to your most important locations.",
                HowToAccess = "Right-click any folder in File Explorer and select 'Pin to Quick access'.",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "pin folders", "favorite folders", "quick access", "fast navigation", "bookmarks folders" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE8B7",
                AccentColor = "#FFB900"
            },
            new WindowsFeature
            {
                Id = "file-explorer-tabs",
                Name = "File Explorer Tabs",
                SimpleExplanation = "Use tabs in File Explorer, just like a web browser.",
                DetailedExplanation = "File Explorer in Windows 11 supports tabs, letting you work with multiple folders in a single window.",
                WhatItDoes = "Opens multiple folder locations as tabs within one File Explorer window.",
                WhyUseful = "Keep your desktop clean while working with multiple folders simultaneously.",
                HowToAccess = "Open File Explorer and press Ctrl + T for a new tab, or click the + button.",
                KeyboardShortcut = "Ctrl + T",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                MinVersion = WindowsVersionRequirement.Windows11Version22H2,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "tabs in explorer", "multiple folders", "file explorer tabs", "browser tabs for files" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE8A0",
                AccentColor = "#FFB900"
            },
            new WindowsFeature
            {
                Id = "power-rename",
                Name = "PowerRename",
                SimpleExplanation = "Rename dozens of files at once using search and replace.",
                DetailedExplanation = "PowerRename (part of PowerToys) lets you bulk rename files using find-and-replace, regex patterns, and file name modification.",
                WhatItDoes = "Batch rename multiple files simultaneously with advanced options.",
                WhyUseful = "Instead of renaming files one by one, rename hundreds in seconds with flexible rules.",
                HowToAccess = "Install Microsoft PowerToys, then right-click files and select 'PowerRename'.",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.ChangesSettings,
                RequiresAdmin = false,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "rename many files", "batch rename", "bulk rename", "rename multiple files", "rename files at once" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 7.0,
                CanLaunch = true,
                LaunchCommand = "powertoys",
                IconGlyph = "\uE8D1",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "file-history",
                Name = "File History",
                SimpleExplanation = "Automatically back up your files so you can recover older versions.",
                DetailedExplanation = "File History continuously backs up versions of your files in Documents, Music, Pictures, Videos, and Desktop folders.",
                WhatItDoes = "Automatically saves backup copies of your files at regular intervals.",
                WhyUseful = "Recover accidentally deleted or modified files from any point in time.",
                HowToAccess = "Settings > Update & Security > Backup > Add a drive, then turn on File History.",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                SettingsUri = "ms-settings:backup",
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "backup files", "recover deleted files", "file version", "restore files", "backup important data" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "compress-folders",
                Name = "Compressed Folders (ZIP)",
                SimpleExplanation = "Create ZIP files without installing any extra software.",
                DetailedExplanation = "Windows has built-in support for creating and extracting ZIP compressed folders.",
                WhatItDoes = "Creates compressed ZIP archives from any folder or selection of files.",
                WhyUseful = "Reduce file sizes for storage or sharing, and organize multiple files into a single archive.",
                HowToAccess = "Right-click files or folders > Send to > Compressed (zipped) folder.",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "zip files", "compress files", "archive files", "reduce file size", "create zip" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "recent-files",
                Name = "Recent Files & Frequent Folders",
                SimpleExplanation = "Quickly access files and folders you've used recently.",
                DetailedExplanation = "File Explorer automatically tracks your recently opened files and frequently accessed folders for quick access.",
                WhatItDoes = "Shows a list of your most recently accessed files and frequently used folders.",
                WhyUseful = "Quickly jump back to files you were working on without navigating through folder structures.",
                HowToAccess = "Open File Explorer and look at 'Quick access' or press Win + E.",
                KeyboardShortcut = "Win + E",
                Category = FeatureCategory.FileManagement,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "recent files", "recently opened", "last files", "open recent", "frequent folders" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE8B7",
                AccentColor = "#0078D4"
            },

            // ========== SYSTEM TOOLS ==========
            new WindowsFeature
            {
                Id = "resource-monitor",
                Name = "Resource Monitor",
                SimpleExplanation = "See exactly what your computer is doing in real time.",
                DetailedExplanation = "Resource Monitor shows detailed real-time information about hardware and software resources including CPU, memory, disk, and network usage.",
                WhatItDoes = "Displays real-time CPU, memory, disk, and network usage per process.",
                WhyUseful = "Find out which program is slowing down your computer, using too much memory, or hogging your internet.",
                HowToAccess = "Press Ctrl + Shift + Esc to open Task Manager, go to Performance tab, click 'Open Resource Monitor'.",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "resmon.exe",
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "what is using my cpu", "memory usage", "network usage", "slow computer", "system performance", "what is using my internet" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE9D9",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "disk-cleanup",
                Name = "Disk Cleanup & Storage Sense",
                SimpleExplanation = "Automatically free up space on your hard drive.",
                DetailedExplanation = "Disk Cleanup removes temporary files and system junk. Storage Sense automatically manages storage by cleaning up files you don't need.",
                WhatItDoes = "Removes temporary files, system cache, and old Windows updates to free disk space.",
                WhyUseful = "Recover gigabytes of storage space taken up by temporary files and system cache you don't need.",
                HowToAccess = "Search for 'Disk Cleanup' in the Start menu, or Settings > System > Storage.",
                SettingsUri = "ms-settings:storagesense",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "free up storage", "clean disk", "delete temp files", "low disk space", "clean up computer", "free space" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 3.0,
                CanLaunch = true,
                LaunchCommand = "cleanmgr.exe",
                IconGlyph = "\uEDFC",
                AccentColor = "#00B294"
            },
            new WindowsFeature
            {
                Id = "event-viewer",
                Name = "Event Viewer",
                SimpleExplanation = "See a detailed log of everything happening on your computer.",
                DetailedExplanation = "Event Viewer shows detailed logs of system events, errors, warnings, and application events. It's like a black box recorder for your PC.",
                WhatItDoes = "Displays detailed logs of system events, errors, and application activities.",
                WhyUseful = "Diagnose problems, track system changes, and understand what happened when something went wrong.",
                HowToAccess = "Press Win + R, type 'eventvwr.msc', and press Enter.",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "eventvwr.msc",
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "system logs", "error logs", "what happened", "diagnose problems", "system events", "crash logs" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE7BA",
                AccentColor = "#9C27B0"
            },
            new WindowsFeature
            {
                Id = "system-file-checker",
                Name = "System File Checker (SFC)",
                SimpleExplanation = "Find and fix broken Windows files automatically.",
                DetailedExplanation = "SFC scans all protected system files and replaces corrupted files with cached copies.",
                WhatItDoes = "Scans and repairs corrupted or missing Windows system files.",
                WhyUseful = "Fix mysterious Windows problems, crashes, and errors caused by corrupted system files.",
                HowToAccess = "Open Command Prompt as Administrator and type: sfc /scannow",
                CommandLine = "sfc /scannow",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Administrative,
                RequiresAdmin = true,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "fix windows", "repair system files", "corrupted files", "system repair", "fix errors", "windows problems" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                WarningMessage = "This requires administrator privileges and scans system files. It's safe but may take several minutes.",
                IconGlyph = "\uE777",
                AccentColor = "#D32F2F"
            },
            new WindowsFeature
            {
                Id = "control-panel",
                Name = "Classic Control Panel",
                SimpleExplanation = "Access the old-school Control Panel with all detailed settings.",
                DetailedExplanation = "While Microsoft pushes the Settings app, the classic Control Panel still has many detailed options not available anywhere else.",
                WhatItDoes = "Opens the traditional Control Panel with comprehensive system settings.",
                WhyUseful = "Some advanced settings and configurations are only available in the classic Control Panel.",
                HowToAccess = "Press Win + R, type 'control', and press Enter.",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "control.exe",
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "control panel", "old settings", "classic settings", "detailed settings", "advanced settings" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE7C3",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "system-restore",
                Name = "System Restore",
                SimpleExplanation = "Undo system changes without losing your files.",
                DetailedExplanation = "System Restore takes snapshots of your system files and registry. You can roll back to a previous state if something goes wrong.",
                WhatItDoes = "Creates restore points and lets you roll back system changes.",
                WhyUseful = "Recover from bad driver installs, software conflicts, or system changes without losing personal files.",
                HowToAccess = "Search for 'Create a restore point' in Start menu, click System Restore.",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "undo changes", "restore previous version", "rollback", "fix system", "recover system" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "windows-terminal",
                Name = "Windows Terminal",
                SimpleExplanation = "A modern, powerful command-line tool with tabs and themes.",
                DetailedExplanation = "Windows Terminal is a modern terminal application that supports Command Prompt, PowerShell, WSL, and Azure Cloud Shell with tabs, themes, and GPU-accelerated text rendering.",
                WhatItDoes = "A tabbed terminal that supports multiple shell types with modern features.",
                WhyUseful = "Work with multiple command-line tools in one window with a beautiful, customizable interface.",
                HowToAccess = "Search for 'Windows Terminal' in Start menu, or install from the Microsoft Store.",
                Category = FeatureCategory.SystemTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "wt.exe",
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "terminal", "command prompt", "powershell", "cmd", "command line", "console" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE756",
                AccentColor = "#0078D4"
            },

            // ========== PRIVACY & SECURITY ==========
            new WindowsFeature
            {
                Id = "privacy-dashboard",
                Name = "Windows Privacy Dashboard",
                SimpleExplanation = "See and control exactly what data Windows collects about you.",
                DetailedExplanation = "The Privacy Dashboard gives you a centralized view of all the data Windows collects and lets you manage privacy settings for each category.",
                WhatItDoes = "Shows what data Windows collects and lets you control each privacy setting.",
                WhyUseful = "Take control of your privacy by understanding and managing what data is collected.",
                HowToAccess = "Settings > Privacy & Security > Windows permissions.",
                SettingsUri = "ms-settings:privacy",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "privacy", "data collection", "what does windows know", "control privacy", "stop tracking" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE730",
                AccentColor = "#D32F2F"
            },
            new WindowsFeature
            {
                Id = "bitlocker",
                Name = "BitLocker Drive Encryption",
                SimpleExplanation = "Encrypt your hard drive so nobody can access your data if your PC is stolen.",
                DetailedExplanation = "BitLocker encrypts your entire drive, making data unreadable without the encryption key. It protects data even if the drive is removed.",
                WhatItDoes = "Encrypts your entire hard drive to protect data from unauthorized access.",
                WhyUseful = "If your laptop is stolen, the thief cannot access any of your files without your password.",
                HowToAccess = "Control Panel > BitLocker Drive Encryption, or Settings > Privacy & Security > Device encryption.",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "encrypt drive", "protect data", "laptop security", "drive encryption", "protect files", "device encryption" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE72E",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "windows-defender",
                Name = "Windows Security Center",
                SimpleExplanation = "Your built-in antivirus and security dashboard.",
                DetailedExplanation = "Windows Security provides real-time protection against viruses, ransomware, and malware, plus firewall and account protection.",
                WhatItDoes = "Manages antivirus, firewall, and all security features from one dashboard.",
                WhyUseful = "Monitor your computer's security status and configure protections in one place.",
                HowToAccess = "Search for 'Windows Security' in Start menu.",
                CanLaunch = true,
                LaunchCommand = "windowsdefender:",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "virus", "antivirus", "malware", "security", "firewall", "protect computer" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE730",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "find-my-device",
                Name = "Find My Device",
                SimpleExplanation = "Locate your laptop if it's lost or stolen.",
                DetailedExplanation = "Find My Device lets you locate your Windows device on a map, lock it remotely, or erase its data.",
                WhatItDoes = "Tracks your device's location and lets you lock or erase it remotely.",
                WhyUseful = "Recover a lost or stolen laptop by locating it or protecting your data remotely.",
                HowToAccess = "Settings > Privacy & Security > Find my device, or sign in at account.microsoft.com/devices.",
                SettingsUri = "ms-settings:findmydevice",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "lost laptop", "stolen laptop", "find device", "locate device", "track laptop" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE707",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "credential-manager",
                Name = "Credential Manager",
                SimpleExplanation = "See all the passwords Windows has saved for you.",
                DetailedExplanation = "Credential Manager stores your saved usernames, passwords, and certificates for websites, apps, and networks.",
                WhatItDoes = "Manages all saved passwords, credentials, and certificates stored by Windows.",
                WhyUseful = "View, edit, or remove saved passwords for websites and applications.",
                HowToAccess = "Control Panel > Credential Manager, or search 'Credential Manager' in Start menu.",
                CanLaunch = true,
                LaunchCommand = "control /name Microsoft.CredentialManager",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "saved passwords", "credentials", "manage passwords", "view passwords", "password manager" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE8D7",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "ransomware-protection",
                Name = "Ransomware Protection (Controlled Folder Access)",
                SimpleExplanation = "Block unauthorized apps from encrypting your files.",
                DetailedExplanation = "Controlled Folder Access protects your important files from ransomware by preventing unauthorized apps from modifying them.",
                WhatItDoes = "Blocks suspicious apps from changing files in protected folders.",
                WhyUseful = "Protects your documents, photos, and files from being encrypted by ransomware.",
                HowToAccess = "Windows Security > Virus & threat protection > Ransomware protection.",
                Category = FeatureCategory.PrivacySecurity,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "ransomware", "protect files", "folder protection", "block malware", "file protection" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE72E",
                AccentColor = "#D32F2F"
            },

            // ========== PERFORMANCE ==========
            new WindowsFeature
            {
                Id = "startup-apps",
                Name = "Startup Apps Manager",
                SimpleExplanation = "Control which apps start automatically when Windows boots up.",
                DetailedExplanation = "Windows lets you see and control which apps launch at startup. Disabling unnecessary startup apps can dramatically speed up boot time.",
                WhatItDoes = "Shows all apps that start automatically with Windows and lets you enable/disable them.",
                WhyUseful = "Speed up your computer's startup by disabling apps you don't need running immediately.",
                HowToAccess = "Settings > Apps > Startup, or Task Manager > Startup tab.",
                SettingsUri = "ms-settings:startupapps",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "slow startup", "boot speed", "startup apps", "autostart", "fast boot", "slow computer", "stop apps from starting" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE74E",
                AccentColor = "#FF8C00"
            },
            new WindowsFeature
            {
                Id = "power-options",
                Name = "Power Options & Plans",
                SimpleExplanation = "Choose between performance and battery life.",
                DetailedExplanation = "Power Options let you choose how Windows manages performance vs. energy consumption. You can create custom power plans.",
                WhatItDoes = "Configures how Windows balances performance with energy consumption.",
                WhyUseful = "Get more performance when plugged in, or extend battery life on the go.",
                HowToAccess = "Settings > System > Power & battery, or Control Panel > Power Options.",
                SettingsUri = "ms-settings:powersleep",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "battery life", "power plan", "performance mode", "save battery", "power settings", "energy settings" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE770",
                AccentColor = "#FF8C00"
            },
            new WindowsFeature
            {
                Id = "memory-diagnostics",
                Name = "Windows Memory Diagnostic",
                SimpleExplanation = "Test your computer's memory (RAM) for problems.",
                DetailedExplanation = "Memory Diagnostic checks your RAM for errors that could cause crashes, blue screens, or data corruption.",
                WhatItDoes = "Runs a comprehensive test of your computer's RAM to find memory errors.",
                WhyUseful = "Diagnose random crashes, blue screens, and system instability caused by faulty memory.",
                HowToAccess = "Search for 'Windows Memory Diagnostic' in Start menu.",
                CanLaunch = true,
                LaunchCommand = "mdsched.exe",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                WarningMessage = "Requires restarting your computer to run the test.",
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "memory test", "ram test", "blue screen", "random crashes", "memory problems", "check ram" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE9D9",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "power-toys",
                Name = "Microsoft PowerToys",
                SimpleExplanation = "A collection of powerful tools to customize and boost Windows.",
                DetailedExplanation = "PowerToys is a free set of utilities from Microsoft for power users to customize Windows and improve productivity.",
                WhatItDoes = "Provides utilities like FancyZones, File Locksmith, Color Picker, Keyboard Manager, and more.",
                WhyUseful = "Supercharge your Windows experience with advanced window management, file locking, and productivity tools.",
                HowToAccess = "Install from the Microsoft Store or GitHub: github.com/microsoft/PowerToys",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "powertoys",
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" }, new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "powertoys", "window manager", "fancyzones", "color picker", "keyboard manager", "productivity tools", "windows customization tools" },
                UsefulnessScore = 9.5,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE74E",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "fast-startup",
                Name = "Fast Startup",
                SimpleExplanation = "Make Windows boot faster by loading part of the system from a saved state.",
                DetailedExplanation = "Fast Startup uses a hybrid shutdown to speed up boot times by saving the kernel state to disk.",
                WhatItDoes = "Reduces boot time by saving the kernel session to disk during shutdown.",
                WhyUseful = "Significantly reduces the time it takes for Windows to start up.",
                HowToAccess = "Control Panel > Power Options > Choose what the power buttons do > Turn on fast startup.",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "fast boot", "boot speed", "quick startup", "faster startup", "boot time" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE74E",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "windows-update",
                Name = "Windows Update Advanced Options",
                SimpleExplanation = "Control when and how Windows updates your computer.",
                DetailedExplanation = "Advanced options let you pause updates, choose when to install them, and manage update behavior more granularly.",
                WhatItDoes = "Gives you control over Windows Update behavior including pausing and scheduling.",
                WhyUseful = "Prevent unexpected restarts and control when updates are installed.",
                HowToAccess = "Settings > Windows Update > Advanced options.",
                SettingsUri = "ms-settings:windowsupdate-options",
                Category = FeatureCategory.Performance,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "pause updates", "delay updates", "control updates", "update schedule", "stop auto update" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },

            // ========== CUSTOMIZATION ==========
            new WindowsFeature
            {
                Id = "personalization",
                Name = "Personalization Hub",
                SimpleExplanation = "Make Windows look and feel exactly how you want.",
                DetailedExplanation = "The Personalization settings let you customize themes, colors, backgrounds, sounds, lock screen, and Start menu.",
                WhatItDoes = "Central hub for customizing Windows appearance and behavior.",
                WhyUseful = "Make your PC feel personal by customizing every visual aspect to your taste.",
                HowToAccess = "Right-click the desktop > Personalize, or Settings > Personalization.",
                SettingsUri = "ms-settings:personalization",
                Category = FeatureCategory.Customization,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "change theme", "customize windows", "change wallpaper", "colors", "personalize", "change background" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE790",
                AccentColor = "#9C27B0"
            },
            new WindowsFeature
            {
                Id = "dark-mode",
                Name = "Dark Mode",
                SimpleExplanation = "Switch Windows to a dark color scheme that's easier on your eyes.",
                DetailedExplanation = "Dark Mode applies a dark color scheme across Windows and supported apps, reducing eye strain in low-light environments.",
                WhatItDoes = "Changes the system-wide color scheme to dark colors.",
                WhyUseful = "Reduces eye strain, saves battery on OLED screens, and looks great.",
                HowToAccess = "Settings > Personalization > Colors > Choose your mode: Dark.",
                Category = FeatureCategory.Customization,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "dark mode", "dark theme", "night mode", "dark colors", "eye strain" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE708",
                AccentColor = "#333333"
            },
            new WindowsFeature
            {
                Id = "accent-colors",
                Name = "Accent Colors",
                SimpleExplanation = "Choose a color that appears across Windows elements like the taskbar and Start menu.",
                DetailedExplanation = "Accent colors let you choose a highlight color that appears on tiles, Start menu, taskbar, and other Windows elements.",
                WhatItDoes = "Sets a highlight color used across the Windows interface.",
                WhyUseful = "Add your personal touch to Windows with your favorite color.",
                HowToAccess = "Settings > Personalization > Colors > Accent color.",
                Category = FeatureCategory.Customization,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "accent color", "change color", "highlight color", "theme color", "start menu color" },
                UsefulnessScore = 6.0,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE790",
                AccentColor = "#9C27B0"
            },
            new WindowsFeature
            {
                Id = "lock-screen-customization",
                Name = "Lock Screen Customization",
                SimpleExplanation = "Make your lock screen show useful info and beautiful images.",
                DetailedExplanation = "Customize your lock screen with Windows Spotlight images, app notifications, and quick status displays.",
                WhatItDoes = "Configures what appears on your lock screen including images and app status.",
                WhyUseful = "See useful information at a glance without unlocking your computer.",
                HowToAccess = "Settings > Personalization > Lock screen.",
                SettingsUri = "ms-settings:lockscreen",
                Category = FeatureCategory.Customization,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "lock screen", "login screen", "screen background", "windows spotlight" },
                UsefulnessScore = 6.5,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE785",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "transparency-effects",
                Name = "Transparency Effects",
                SimpleExplanation = "Add a glass-like transparent effect to Windows surfaces.",
                DetailedExplanation = "Transparency effects (Acrylic) make the taskbar, Start menu, and other surfaces semi-transparent.",
                WhatItDoes = "Adds transparency to taskbar, Start menu, and other Windows surfaces.",
                WhyUseful = "Creates a modern, elegant look and lets you see your wallpaper through UI elements.",
                HowToAccess = "Settings > Personalization > Colors > Transparency effects.",
                Category = FeatureCategory.Customization,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "transparency", "transparent taskbar", "glass effect", "acrylic", "blur" },
                UsefulnessScore = 6.5,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE790",
                AccentColor = "#9C27B0"
            },

            // ========== KEYBOARD SHORTCUTS ==========
            new WindowsFeature
            {
                Id = "win-keyboard-shortcuts",
                Name = "Essential Windows Keyboard Shortcuts",
                SimpleExplanation = "Master the shortcuts that make you 10x faster on Windows.",
                DetailedExplanation = "Windows has dozens of keyboard shortcuts that can dramatically speed up your workflow.",
                WhatItDoes = "Provides a reference for the most useful Windows keyboard shortcuts.",
                WhyUseful = "Save time on repetitive tasks and work more efficiently.",
                HowToAccess = "Press Win + / for a cheat sheet (Windows 11), or press Win + ? for help.",
                KeyboardShortcut = "Win + /",
                Category = FeatureCategory.KeyboardShortcuts,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" }, new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "keyboard shortcuts", "hotkeys", "shortcuts list", "speed up", "keyboard commands", "fast typing" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE765",
                AccentColor = "#FF8C00"
            },
            new WindowsFeature
            {
                Id = "emoji-shortcut",
                Name = "Emoji & Symbols Panel",
                SimpleExplanation = "Access emojis, GIFs, and special characters from a built-in panel.",
                DetailedExplanation = "Windows has a built-in emoji picker that works in any text field, with emojis, kaomoji, symbols, and even GIF search.",
                WhatItDoes = "Opens a panel with emojis, symbols, kaomojis, and GIFs.",
                WhyUseful = "Add emojis and special characters to any text without memorizing codes.",
                HowToAccess = "Press Win + . (period) or Win + ; (semicolon) in any text field.",
                KeyboardShortcut = "Win + .",
                Category = FeatureCategory.KeyboardShortcuts,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "emojis", "emoji keyboard", "special characters", "symbols", "gifs", "kaomoji" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE765",
                AccentColor = "#FF8C00"
            },
            new WindowsFeature
            {
                Id = "dictation-shortcut",
                Name = "Screen Capture Shortcuts",
                SimpleExplanation = "Take screenshots the smart way with built-in tools.",
                DetailedExplanation = "Windows offers multiple screenshot methods: Snipping Tool (Win+Shift+S), Print Screen, and Xbox Game Bar captures.",
                WhatItDoes = "Provides built-in tools for capturing screenshots and screen recordings.",
                WhyUseful = "Quickly capture exactly what you need on screen without extra software.",
                HowToAccess = "Win + Shift + S for snipping, Print Screen for full screen, Alt + Print Screen for active window.",
                KeyboardShortcut = "Win + Shift + S",
                Category = FeatureCategory.KeyboardShortcuts,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "screenshot", "screen capture", "print screen", "snipping tool", "screen recording", "take screenshot" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE740",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "file-explorer-shortcuts",
                Name = "File Explorer Shortcuts",
                SimpleExplanation = "Navigate files and folders at lightning speed.",
                DetailedExplanation = "File Explorer has powerful keyboard shortcuts for quick navigation, selection, and file management.",
                WhatItDoes = "Reference for the most useful File Explorer keyboard shortcuts.",
                WhyUseful = "Navigate folders, rename files, and manage your files without touching the mouse.",
                HowToAccess = "Use shortcuts like Ctrl + N (new window), Alt + Up (parent folder), F2 (rename), Ctrl + Shift + N (new folder).",
                KeyboardShortcut = "Ctrl + N",
                Category = FeatureCategory.KeyboardShortcuts,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "file explorer shortcuts", "navigate files", "folder shortcuts", "file management shortcuts" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE8B7",
                AccentColor = "#FFB900"
            },
            new WindowsFeature
            {
                Id = "virtual-desktop-shortcuts",
                Name = "Virtual Desktop Shortcuts",
                SimpleExplanation = "Switch between virtual desktops instantly.",
                DetailedExplanation = "Keyboard shortcuts for creating, switching, and managing virtual desktops.",
                WhatItDoes = "Provides shortcuts for managing virtual desktops.",
                WhyUseful = "Quickly switch between workspaces without using the mouse.",
                HowToAccess = "Win + Ctrl + D (create), Win + Ctrl + Left/Right (switch), Win + Ctrl + F4 (close).",
                KeyboardShortcut = "Win + Ctrl + D",
                Category = FeatureCategory.KeyboardShortcuts,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "virtual desktop shortcuts", "switch desktop", "create desktop", "desktop shortcuts" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE8A0",
                AccentColor = "#6B4FCF"
            },

            // ========== POWER USER TOOLS ==========
            new WindowsFeature
            {
                Id = "run-dialog",
                Name = "Run Dialog",
                SimpleExplanation = "Open any program, file, or setting by typing its name.",
                DetailedExplanation = "The Run dialog lets you quickly launch programs, open folders, and access system tools by typing their commands.",
                WhatItDoes = "Opens programs, files, folders, and websites by typing a command.",
                WhyUseful = "The fastest way to launch any tool or program if you know its name.",
                HowToAccess = "Press Win + R.",
                KeyboardShortcut = "Win + R",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "run command", "open program", "launch tool", "quick launch", "run dialog" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE74E",
                AccentColor = "#9C27B0"
            },
            new WindowsFeature
            {
                Id = "task-manager",
                Name = "Task Manager",
                SimpleExplanation = "See what's running on your computer and manage it.",
                DetailedExplanation = "Task Manager shows all running processes, performance metrics, startup apps, and lets you force-close unresponsive programs.",
                WhatItDoes = "Monitors and manages running processes, performance, and startup apps.",
                WhyUseful = "Kill frozen apps, monitor performance, and manage what runs at startup.",
                HowToAccess = "Press Ctrl + Shift + Esc, or Ctrl + Alt + Delete.",
                KeyboardShortcut = "Ctrl + Shift + Esc",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "taskmgr.exe",
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "task manager", "kill app", "force close", "running processes", "performance", "what is using my resources" },
                UsefulnessScore = 9.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE9D9",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "power-shell",
                Name = "PowerShell",
                SimpleExplanation = "A powerful command-line tool for automating Windows tasks.",
                DetailedExplanation = "PowerShell is a command-line shell and scripting language built into Windows for system administration and automation.",
                WhatItDoes = "Provides a powerful command-line interface for system administration.",
                WhyUseful = "Automate repetitive tasks, manage system settings, and perform advanced operations.",
                HowToAccess = "Search for 'PowerShell' in Start menu, or right-click Start > Windows Terminal.",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Safe,
                CanLaunch = true,
                LaunchCommand = "powershell.exe",
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "powershell", "command line", "scripting", "automation", "admin tools" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE756",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "wsl",
                Name = "Windows Subsystem for Linux (WSL)",
                SimpleExplanation = "Run Linux directly on Windows without a virtual machine.",
                DetailedExplanation = "WSL lets you run a real Linux environment directly on Windows, including command-line tools, utilities, and applications.",
                WhatItDoes = "Runs a full Linux environment alongside Windows.",
                WhyUseful = "Use Linux tools and development environments without dual-booting or virtual machines.",
                HowToAccess = "Open PowerShell as Admin and run: wsl --install",
                CommandLine = "wsl --install",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Administrative,
                RequiresAdmin = true,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "linux on windows", "wsl", "linux tools", "ubuntu on windows", "dual boot alternative" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 6.0,
                WarningMessage = "This installs a Linux distribution on your system. It requires administrator privileges.",
                IconGlyph = "\uE756",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "registry-editor",
                Name = "Registry Editor",
                SimpleExplanation = "Access and modify Windows' internal configuration database.",
                DetailedExplanation = "Registry Editor lets you view and edit the Windows registry, which controls most system settings and behavior.",
                WhatItDoes = "Provides direct access to Windows configuration settings at the system level.",
                WhyUseful = "Make advanced changes to Windows behavior not available through normal settings.",
                HowToAccess = "Press Win + R, type 'regedit', and press Enter.",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Expert,
                Safety = SafetyLevel.SystemImpact,
                RequiresAdmin = true,
                CanLaunch = true,
                LaunchCommand = "regedit.exe",
                Tags = new List<FeatureTag> { new() { Label = "Expert", Icon = "🔴", Color = "#D32F2F" } },
                SearchIntents = new List<string> { "registry", "regedit", "system configuration", "advanced settings", "modify windows behavior" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 5.0,
                WarningMessage = "Incorrect registry changes can cause system instability. Only make changes if you know what you're doing.",
                IconGlyph = "\uE7C3",
                AccentColor = "#D32F2F"
            },
            new WindowsFeature
            {
                Id = "group-policy",
                Name = "Local Group Policy Editor",
                SimpleExplanation = "Control advanced Windows rules and behavior.",
                DetailedExplanation = "Group Policy Editor lets you configure administrative templates and policies that control Windows behavior at a deeper level than Settings.",
                WhatItDoes = "Manages system policies that control Windows behavior and features.",
                WhyUseful = "Control advanced Windows behavior that isn't available in the normal Settings app.",
                HowToAccess = "Press Win + R, type 'gpedit.msc', and press Enter.",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Administrative,
                RequiresAdmin = true,
                CanLaunch = true,
                LaunchCommand = "gpedit.msc",
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "group policy", "advanced settings", "system rules", "policy editor", "admin settings" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE7C3",
                AccentColor = "#9C27B0"
            },
            new WindowsFeature
            {
                Id = "compressed-folder-extract",
                Name = "Built-in ZIP Support",
                SimpleExplanation = "Create and extract ZIP files without any extra software.",
                DetailedExplanation = "Windows natively supports creating and extracting ZIP compressed folders.",
                WhatItDoes = "Compresses and decompresses ZIP archives.",
                WhyUseful = "No need to install WinRAR or 7-Zip for basic compression needs.",
                HowToAccess = "Right-click > Send to > Compressed folder, or right-click > Extract All.",
                Category = FeatureCategory.PowerUserTools,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "zip files", "compress files", "extract zip", "zip utility" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },

            // ========== ACCESSIBILITY ==========
            new WindowsFeature
            {
                Id = "magnifier",
                Name = "Magnifier",
                SimpleExplanation = "Zoom in on any part of your screen.",
                DetailedExplanation = "Magnifier enlarges all or part of your screen for better visibility. It supports full screen, lens, and docked modes.",
                WhatItDoes = "Zooms in on screen content for better visibility.",
                WhyUseful = "Read small text, see details clearly, or present content to others.",
                HowToAccess = "Press Win + Plus (+) to turn on, Win + Esc to turn off.",
                KeyboardShortcut = "Win + +",
                Category = FeatureCategory.Accessibility,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "magnifier", "zoom in", "screen magnifier", "enlarge screen", "read small text" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE7A6",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "narrator",
                Name = "Narrator",
                SimpleExplanation = "Have Windows read text aloud to you.",
                DetailedExplanation = "Narrator is a built-in screen reader that reads text on your screen using synthesized speech.",
                WhatItDoes = "Reads aloud text and UI elements on your screen.",
                WhyUseful = "Useful for visually impaired users or when you want your screen content read aloud.",
                HowToAccess = "Press Win + Ctrl + Enter to toggle Narrator.",
                KeyboardShortcut = "Win + Ctrl + Enter",
                Category = FeatureCategory.Accessibility,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "narrator", "screen reader", "read aloud", "text to speech", "accessibility reading" },
                UsefulnessScore = 6.5,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE767",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "color-filter",
                Name = "Color Filters",
                SimpleExplanation = "Adjust screen colors to help with color vision.",
                DetailedExplanation = "Color filters apply adjustments to the entire screen to help users with color blindness or light sensitivity.",
                WhatItDoes = "Applies color adjustments to help with color vision deficiencies.",
                WhyUseful = "Makes the screen easier to see for people with color blindness or visual sensitivities.",
                HowToAccess = "Settings > Accessibility > Color filters.",
                SettingsUri = "ms-settings:easeofaccess-colorfilter",
                Category = FeatureCategory.Accessibility,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "color blind", "color filter", "color correction", "visual accessibility", "night colors" },
                UsefulnessScore = 6.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE790",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "voice-access",
                Name = "Voice Access",
                SimpleExplanation = "Control your entire PC with just your voice.",
                DetailedExplanation = "Voice Access lets you control your PC, open apps, browse the web, and edit text using only your voice.",
                WhatItDoes = "Provides voice control over the entire Windows interface.",
                WhyUseful = "Hands-free computer control for accessibility or convenience.",
                HowToAccess = "Settings > Accessibility > Voice access, or press Win + Ctrl + S.",
                KeyboardShortcut = "Win + Ctrl + S",
                Category = FeatureCategory.Accessibility,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "voice control", "control by voice", "hands free", "voice access", "speak to control" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE767",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "eye-control",
                Name = "Eye Control",
                SimpleExplanation = "Control Windows using eye tracking technology.",
                DetailedExplanation = "Eye Control lets you operate Windows using eye tracking devices, controlling the mouse, keyboard, and text-to-speech.",
                WhatItDoes = "Enables PC control through eye tracking technology.",
                WhyUseful = "Essential for users with limited mobility who need hands-free control.",
                HowToAccess = "Settings > Accessibility > Eye control (requires compatible eye tracker).",
                SettingsUri = "ms-settings:easeofaccess-eyecontrol",
                Category = FeatureCategory.Accessibility,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Expert", Icon = "🔴", Color = "#D32F2F" } },
                SearchIntents = new List<string> { "eye control", "eye tracking", "hands free control", "accessibility control" },
                UsefulnessScore = 5.0,
                DiscoveryDifficulty = 8.0,
                IconGlyph = "\uE7A6",
                AccentColor = "#0078D4"
            },

            // ========== NETWORKING ==========
            new WindowsFeature
            {
                Id = "network-status",
                Name = "Network Status Dashboard",
                SimpleExplanation = "See everything about your network connection at a glance.",
                DetailedExplanation = "The Network status page shows connection details, data usage, and lets you manage network settings.",
                WhatItDoes = "Displays network connection status, speed, and data usage details.",
                WhyUseful = "Quickly diagnose network problems and monitor data usage.",
                HowToAccess = "Settings > Network & Internet > Status.",
                SettingsUri = "ms-settings:network-status",
                Category = FeatureCategory.Networking,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "network status", "connection problems", "internet speed", "wifi status", "network settings" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 2.0,
                IconGlyph = "\uE774",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "mobile-hotspot",
                Name = "Mobile Hotspot",
                SimpleExplanation = "Share your internet connection with other devices.",
                DetailedExplanation = "Mobile Hotspot lets you share your PC's internet connection with other devices via Wi-Fi.",
                WhatItDoes = "Creates a Wi-Fi hotspot using your PC's internet connection.",
                WhyUseful = "Share your wired or cellular internet with phones, tablets, and other devices.",
                HowToAccess = "Settings > Network & Internet > Mobile hotspot.",
                SettingsUri = "ms-settings:network-mobilehotspot",
                Category = FeatureCategory.Networking,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "mobile hotspot", "share internet", "wifi hotspot", "tethering", "share connection" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE774",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "network-profile",
                Name = "Network Profile (Public/Private)",
                SimpleExplanation = "Control whether your PC is discoverable on the network.",
                DetailedExplanation = "Network profiles control firewall rules and network discovery. Public hides your PC, Private allows sharing.",
                WhatItDoes = "Sets whether your PC is discoverable and what network features are available.",
                WhyUseful = "Protect your PC on public networks or enable sharing on trusted home networks.",
                HowToAccess = "Settings > Network & Internet > Wi-Fi > [Your network] > Network profile type.",
                Category = FeatureCategory.Networking,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "network profile", "public network", "private network", "network discovery", "firewall" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE774",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "data-usage",
                Name = "Data Usage Monitor",
                SimpleExplanation = "See how much data each app is using.",
                DetailedExplanation = "Windows tracks data usage per app, showing you exactly which apps consume the most bandwidth.",
                WhatItDoes = "Shows data usage broken down by each application.",
                WhyUseful = "Find bandwidth-hogging apps and manage your data consumption.",
                HowToAccess = "Settings > Network & Internet > Data usage.",
                SettingsUri = "ms-settings:datausage",
                Category = FeatureCategory.Networking,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" } },
                SearchIntents = new List<string> { "data usage", "bandwidth", "internet usage", "data monitor", "app data usage" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 4.0,
                IconGlyph = "\uE774",
                AccentColor = "#0078D4"
            },

            // ========== TROUBLESHOOTING ==========
            new WindowsFeature
            {
                Id = "troubleshoot",
                Name = "Windows Troubleshooters",
                SimpleExplanation = "Let Windows diagnose and fix common problems automatically.",
                DetailedExplanation = "Built-in troubleshooters can automatically diagnose and fix issues with networking, printing, audio, Windows Update, and more.",
                WhatItDoes = "Runs automated diagnostics and fixes for common Windows problems.",
                WhyUseful = "Fix common issues without technical knowledge - Windows does the work for you.",
                HowToAccess = "Settings > System > Troubleshoot > Other troubleshooters.",
                SettingsUri = "ms-settings:troubleshoot",
                Category = FeatureCategory.Troubleshooting,
                Difficulty = DifficultyLevel.Beginner,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Beginner Friendly", Icon = "🟢", Color = "#4CAF50" }, new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "fix problems", "diagnose", "troubleshoot", "repair", "fix issues", "windows problems" },
                UsefulnessScore = 8.5,
                DiscoveryDifficulty = 3.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "safe-mode",
                Name = "Safe Mode",
                SimpleExplanation = "Start Windows with only the essentials to fix problems.",
                DetailedExplanation = "Safe Mode starts Windows with minimal drivers and services, making it easier to diagnose and fix problems.",
                WhatItDoes = "Boots Windows with a minimal set of drivers and services.",
                WhyUseful = "Fix problems that prevent Windows from starting normally, like driver conflicts or malware.",
                HowToAccess = "Settings > Recovery > Advanced startup > Restart now > Troubleshoot > Startup Settings > Safe Mode.",
                Category = FeatureCategory.Troubleshooting,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "safe mode", "boot safe mode", "fix boot", "startup problems", "recovery mode" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE777",
                AccentColor = "#D32F2F"
            },
            new WindowsFeature
            {
                Id = "bsod-troubleshooting",
                Name = "Blue Screen Troubleshooting",
                SimpleExplanation = "Diagnose and fix blue screen errors.",
                DetailedExplanation = "Windows includes tools and information to help diagnose and resolve blue screen (BSOD) errors.",
                WhatItDoes = "Provides diagnostics and solutions for blue screen errors.",
                WhyUseful = "Quickly identify and fix the cause of blue screen crashes.",
                HowToAccess = "Settings > System > Recovery, or search 'Blue Screen' in Settings.",
                Category = FeatureCategory.Troubleshooting,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "blue screen", "bsod", "crash", "system crash", "stop error" },
                UsefulnessScore = 7.5,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE777",
                AccentColor = "#D32F2F"
            },
            new WindowsFeature
            {
                Id = "performance-monitor",
                Name = "Performance Monitor",
                SimpleExplanation = "Monitor your computer's performance in real time with detailed graphs.",
                DetailedExplanation = "Performance Monitor provides detailed real-time and historical performance data with customizable counters and reports.",
                WhatItDoes = "Displays detailed performance metrics with customizable graphs and reports.",
                WhyUseful = "Deep-dive into performance issues with detailed system monitoring.",
                HowToAccess = "Press Win + R, type 'perfmon', and press Enter.",
                CanLaunch = true,
                LaunchCommand = "perfmon.exe",
                Category = FeatureCategory.Troubleshooting,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Expert", Icon = "🔴", Color = "#D32F2F" } },
                SearchIntents = new List<string> { "performance monitor", "system performance", "performance graphs", "performance tracking" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE9D9",
                AccentColor = "#0078D4"
            },
            new WindowsFeature
            {
                Id = "recovery-drive",
                Name = "Recovery Drive",
                SimpleExplanation = "Create a USB drive that can fix Windows if it won't start.",
                DetailedExplanation = "A recovery drive lets you troubleshoot and fix Windows problems when it can't boot normally.",
                WhatItDoes = "Creates a bootable USB drive for Windows recovery.",
                WhyUseful = "Essential safety net - use it to recover Windows when nothing else works.",
                HowToAccess = "Search for 'Create a recovery drive' in Start menu.",
                Category = FeatureCategory.Troubleshooting,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                WarningMessage = "This will erase the USB drive you use. Make sure it's empty or backed up.",
                Tags = new List<FeatureTag> { new() { Label = "Highly Useful", Icon = "⭐", Color = "#FFD700" } },
                SearchIntents = new List<string> { "recovery drive", "usb recovery", "windows recovery", "emergency boot", "repair windows" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE777",
                AccentColor = "#0078D4"
            },

            // ========== DEVELOPER FEATURES ==========
            new WindowsFeature
            {
                Id = "dev-drive",
                Name = "Dev Drive",
                SimpleExplanation = "A special drive optimized for development work.",
                DetailedExplanation = "Dev Drive is a new storage volume designed for developer workloads with better performance for source control and build operations.",
                WhatItDoes = "Creates a storage volume optimized for development tasks.",
                WhyUseful = "Faster builds, better performance for large codebases and package managers.",
                HowToAccess = "Settings > System > Storage > Disks & volumes > Create Dev Drive.",
                MinVersion = WindowsVersionRequirement.Windows11Version23H2,
                Category = FeatureCategory.DeveloperFeatures,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "dev drive", "development drive", "build performance", "developer storage", "code performance" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE756",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "developer-mode",
                Name = "Developer Mode",
                SimpleExplanation = "Unlock advanced features for app development and sideloading.",
                DetailedExplanation = "Developer Mode enables sideloading apps, device discovery, and additional development features.",
                WhatItDoes = "Unlocks developer features like app sideloading and SSH debugging.",
                WhyUseful = "Essential for app developers and power users who need advanced capabilities.",
                HowToAccess = "Settings > System > For developers > Developer Mode.",
                SettingsUri = "ms-settings:developers",
                Category = FeatureCategory.DeveloperFeatures,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "developer mode", "sideload apps", "dev mode", "developer settings" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE756",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "hyper-v",
                Name = "Hyper-V",
                SimpleExplanation = "Run virtual machines directly on Windows.",
                DetailedExplanation = "Hyper-V lets you create and run virtual machines, allowing you to run other operating systems alongside Windows.",
                WhatItDoes = "Creates and manages virtual machines on your Windows PC.",
                WhyUseful = "Test different operating systems, run isolated environments, and experiment safely.",
                HowToAccess = "Enable in Settings > System > Optional features > More Windows features > Hyper-V.",
                Category = FeatureCategory.DeveloperFeatures,
                Difficulty = DifficultyLevel.Advanced,
                Safety = SafetyLevel.Safe,
                RequiresAdmin = true,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "virtual machine", "hyper-v", "vm", "run other os", "virtualization" },
                UsefulnessScore = 8.0,
                DiscoveryDifficulty = 6.0,
                IconGlyph = "\uE756",
                AccentColor = "#FF4500"
            },
            new WindowsFeature
            {
                Id = "windows-subsystem-android",
                Name = "Windows Subsystem for Android",
                SimpleExplanation = "Run Android apps directly on Windows.",
                DetailedExplanation = "WSA lets you install and run Android apps from the Amazon Appstore directly on Windows.",
                WhatItDoes = "Runs Android applications natively on Windows.",
                WhyUseful = "Use your favorite Android apps without needing an emulator or phone.",
                HowToAccess = "Install from the Microsoft Store (Windows 11 only, limited availability).",
                MinVersion = WindowsVersionRequirement.Windows11Version21H2,
                Category = FeatureCategory.DeveloperFeatures,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Hidden Gem", Icon = "🔥", Color = "#FF4500" } },
                SearchIntents = new List<string> { "android apps", "run android", "windows subsystem android", "android on pc" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 7.0,
                IconGlyph = "\uE756",
                AccentColor = "#4CAF50"
            },
            new WindowsFeature
            {
                Id = "windows-terminal-profiles",
                Name = "Windows Terminal Custom Profiles",
                SimpleExplanation = "Create custom terminal profiles with different shells and looks.",
                DetailedExplanation = "Windows Terminal lets you create profiles for different shells (CMD, PowerShell, WSL) with custom colors, fonts, and settings.",
                WhatItDoes = "Creates customized terminal profiles for different shells and workflows.",
                WhyUseful = "Quickly switch between different environments with your preferred settings.",
                HowToAccess = "Open Windows Terminal > click dropdown > Settings.",
                Category = FeatureCategory.DeveloperFeatures,
                Difficulty = DifficultyLevel.Intermediate,
                Safety = SafetyLevel.Safe,
                Tags = new List<FeatureTag> { new() { Label = "Power User", Icon = "⚡", Color = "#9C27B0" } },
                SearchIntents = new List<string> { "terminal profiles", "custom terminal", "terminal themes", "terminal settings" },
                UsefulnessScore = 7.0,
                DiscoveryDifficulty = 5.0,
                IconGlyph = "\uE756",
                AccentColor = "#0078D4"
            },
        };
    }

    public static List<CategoryInfo> GetCategories()
    {
        return new List<CategoryInfo>
        {
            new() { Category = FeatureCategory.Productivity, DisplayName = "Productivity", Description = "Work smarter and get more done", IconGlyph = "\uE7C3", Color = "#0078D4" },
            new() { Category = FeatureCategory.FileManagement, DisplayName = "File Management", Description = "Organize and manage your files", IconGlyph = "\uE8B7", Color = "#FFB900" },
            new() { Category = FeatureCategory.SystemTools, DisplayName = "System Tools", Description = "Built-in Windows utilities", IconGlyph = "\uE7C3", Color = "#0078D4" },
            new() { Category = FeatureCategory.PrivacySecurity, DisplayName = "Privacy & Security", Description = "Protect your data and privacy", IconGlyph = "\uE730", Color = "#D32F2F" },
            new() { Category = FeatureCategory.Performance, DisplayName = "Performance", Description = "Speed up your PC", IconGlyph = "\uE74E", Color = "#FF8C00" },
            new() { Category = FeatureCategory.Customization, DisplayName = "Customization", Description = "Make Windows your own", IconGlyph = "\uE790", Color = "#9C27B0" },
            new() { Category = FeatureCategory.KeyboardShortcuts, DisplayName = "Keyboard Shortcuts", Description = "Work faster with shortcuts", IconGlyph = "\uE765", Color = "#FF8C00" },
            new() { Category = FeatureCategory.PowerUserTools, DisplayName = "Power User Tools", Description = "Advanced system tools", IconGlyph = "\uE756", Color = "#9C27B0" },
            new() { Category = FeatureCategory.Accessibility, DisplayName = "Accessibility", Description = "Make Windows easier to use", IconGlyph = "\uE7A6", Color = "#0078D4" },
            new() { Category = FeatureCategory.Networking, DisplayName = "Networking", Description = "Network and connectivity", IconGlyph = "\uE774", Color = "#0078D4" },
            new() { Category = FeatureCategory.Troubleshooting, DisplayName = "Troubleshooting", Description = "Fix common problems", IconGlyph = "\uE777", Color = "#D32F2F" },
            new() { Category = FeatureCategory.DeveloperFeatures, DisplayName = "Developer Features", Description = "Tools for developers", IconGlyph = "\uE756", Color = "#FF4500" },
        };
    }
}
